// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsXPWtXNWkXE0KDErkZiWHP3LfaNLxF7k',
    appId: '1:1095699246237:ios:b3a72348bc64a6fbccf874',
    messagingSenderId: '1095699246237',
    projectId: 'final-project-5c901',
    storageBucket: 'final-project-5c901.firebasestorage.app',
    iosBundleId: 'com.example.skillGapAnalyzer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsXPWtXNWkXE0KDErkZiWHP3LfaNLxF7k',
    appId: '1:1095699246237:ios:b3a72348bc64a6fbccf874',
    messagingSenderId: '1095699246237',
    projectId: 'final-project-5c901',
    storageBucket: 'final-project-5c901.firebasestorage.app',
    iosBundleId: 'com.example.skillGapAnalyzer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwgtrF5AYPZSz66xOfFyYM_aoEEv0bAls',
    appId: '1:1095699246237:web:5c8ebc48b1ed17b5ccf874',
    messagingSenderId: '1095699246237',
    projectId: 'final-project-5c901',
    authDomain: 'final-project-5c901.firebaseapp.com',
    storageBucket: 'final-project-5c901.firebasestorage.app',
    measurementId: 'G-MT87YLK0WN',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwgtrF5AYPZSz66xOfFyYM_aoEEv0bAls',
    appId: '1:1095699246237:web:5c8ebc48b1ed17b5ccf874',
    messagingSenderId: '1095699246237',
    projectId: 'final-project-5c901',
    authDomain: 'final-project-5c901.firebaseapp.com',
    storageBucket: 'final-project-5c901.firebasestorage.app',
    measurementId: 'G-MT87YLK0WN',
  );
}
